---
name: sandbox
on:
  schedule:
    - cron: 30 08 * * 1,3,5 # 01:30 PST mon,wed,fri
  push:
    branches:
      - main
      - sa-2025-06-12-toolbox-sandbox # FIXME: remove
    paths:
      - sandbox/**.go
      - sandbox/*/go.*
      - sandbox/**/dagger.json
      - .github/workflows/sandbox.yaml
      - .github/workflows/reusable-toolbox.yaml
  pull_request:
    paths:
      - sandbox/**.go
      - sandbox/*/go.*
      - sandbox/**/dagger.json
      - .github/workflows/sandbox.yaml
      - .github/workflows/reusable-toolbox.yaml
  workflow_dispatch: {}
jobs:
  sandbox:
    name: sandbox
    uses: ./.github/workflows/reusable-toolbox.yaml
    secrets: inherit
    permissions:
      contents: read
      packages: write
      id-token: write
    with:
      module: toolbox/sandbox
      image_name: sandbox-toolbox
      version: latest
      latest: "true"
