---
name: toolbox-fedora
on:
  schedule:
    - cron: 30 08 * * 1,3,5 # 01:30 PST mon,wed,fri
  push:
    branches:
      - main
    paths:
      - toolbox/**.go
      - toolbox/*/go.*
      - toolbox/**/dagger.json
      - .github/workflows/toolbox.yaml
      - .github/workflows/reusable-toolbox.yaml
  pull_request:
    paths:
      - toolbox/**.go
      - toolbox/*/go.*
      - toolbox/**/dagger.json
      - .github/workflows/toolbox.yaml
      - .github/workflows/reusable-toolbox.yaml
  # yamllint disable-line rule:empty-values
  workflow_dispatch:
jobs:
  publish:
    strategy:
      fail-fast: false
      matrix:
        release:
          - version: 41
            latest: false
          - version: 42
            latest: true
    name: toolbox
    uses: ./.github/workflows/reusable-toolbox-build-and-publish.yaml
    secrets: inherit
    permissions:
      contents: read
      packages: write
      id-token: write
    with:
      module: toolbox/fedora
      image_name: fedora-toolbox
      version: ${{ matrix.release.version }}
      latest: ${{ matrix.release.latest }}
